# Site settings
title: ASBC LLC
email: abresler@asbcllc.com
description: "ASBC LLC"
baseurl: ""
url: "http://asbcllc.com"
twitter_username: abresler
github_username:  abresler

# Build settings
markdown: kramdown
permalink: pretty
